---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: create-container
  namespace: song-ansible
  labels:
    app.kubernetes.io/name: hello-song
spec:
  tower_auth_secret: autocon-admin-password
  job_template_name: container-on-cp624
  extra_vars:
    #API_DOMAIN: demo.red-chesterfield.com
    # The AWS Route53 NS Record must exist with NameServers:
    # ns1.f5cloudservices.com
    # ns2.f5cloudservices.com
    #GSLB_ZONE: www-apps
    #BASE_DOMAIN: foxtrot.demo.red-chesterfield.com
